# TCL File Generated by Component Editor 15.1
# Tue May 29 16:29:43 EEST 2018
# DO NOT MODIFY


# 
# custom_rgb_resambler "custom_rgb_resambler" v1.0
#  2018.05.29.16:29:43
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module custom_rgb_resambler
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_rgb_resambler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME custom_rgb_resambler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

